void() Menu_Vote = 
{
	self.current_menu = 23;
	if (self.vote_menu == 0)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ 1on1fort \n€”‚ 1on1fortc \n€•‚ 1on1forts \n€–‚ 1on1r \n€—‚ 1on1r2 \n€˜‚ 1on1rpro \n€™‚ 2castles \n€š‚ 2farms \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 1)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ 2farms_olde \n€”‚ 2fort4r \n€•‚ 2FORT5 \n€–‚ 2fort5fel \n€—‚ 2fort5p \n€˜‚ 2fort5r \n€™‚ 2fort5sta \n€š‚ 2fortflood \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 2)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ 2mach1 \n€”‚ 2machse \n€•‚ 2mfield4 \n€–‚ 2mtf5 \n€—‚ 2night2 \n€˜‚ 2nuke2 \n€™‚ 2octa4v1 \n€š‚ 2on2fortb2 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 3)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ 2skool3 \n€”‚ 2sphinx6 \n€•‚ 2tech4 \n€–‚ 32smooth \n€—‚ 32smoothfel \n€˜‚ 32smoothsta \n€™‚ 4f4 \n€š‚ 4f5_havoc \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 4)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ adjmpvb3 \n€”‚ adjmpvf1 \n€•‚ airfox \n€–‚ alcatraz \n€—‚ arenasix \n€˜‚ autobase \n€™‚ avihous \n€š‚ aztec1 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 5)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ bam4 \n€”‚ bam4sta \n€•‚ bam4_mega \n€–‚ bases \n€—‚ beer \n€˜‚ beer2 \n€™‚ bfort \n€š‚ blitzkrieg2 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 6)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ blitzkrieg2_mega \n€”‚ blue1 \n€•‚ border1 \n€–‚ border1r \n€—‚ box3 \n€˜‚ brdgdeth \n€™‚ breach2 \n€š‚ bridge2 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 7)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ bridgep \n€”‚ bringit \n€•‚ bunnyhop \n€–‚ bunyhop2 \n€—‚ canalzon \n€˜‚ canyon1 \n€™‚ caverns \n€š‚ choosenow \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 8)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ church \n€”‚ circle \n€•‚ circle1 \n€–‚ cjump1r \n€—‚ crap1on1 \n€˜‚ cryptic1 \n€™‚ cube \n€š‚ demorox5 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 9)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ demoz3 \n€”‚ dinner \n€•‚ disorder \n€–‚ ditch2 \n€—‚ dune1 \n€˜‚ dune1sta \n€™‚ egypt \n€š‚ Empbat \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 10)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ endif \n€”‚ engbat \n€•‚ engbatxr \n€–‚ engjump2 \n€—‚ engjumps \n€˜‚ excel \n€™‚ extrj2b3 \n€š‚ f4f \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 11)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ fcast \n€”‚ flagcap \n€•‚ flash3e \n€–‚ FLASH3~1 \n€—‚ free4all2 \n€˜‚ freeway \n€™‚ frontlin \n€š‚ futureq \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 12)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ h4rdcore \n€”‚ helo_sub4 \n€•‚ hunt2000 \n€–‚ hunted \n€—‚ huntedr \n€˜‚ iceland3 \n€™‚ impact1 \n€š‚ insanity2 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 13)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ invade4a \n€”‚ jgpcity4 \n€•‚ knockout \n€–‚ mbasesr \n€—‚ medic \n€˜‚ medic3rr \n€™‚ mini32s \n€š‚ mininoheros \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 14)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ nano2 \n€”‚ noheros \n€•‚ p1on12 \n€–‚ p1on1vF \n€—‚ parafort2 \n€˜‚ pipejump \n€™‚ pipelan \n€š‚ pipes \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 15)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ povhop02 \n€”‚ povmed2 \n€•‚ preskool \n€–‚ pskills \n€—‚ psq1f \n€˜‚ qdeth3 \n€™‚ rckteer \n€š‚ rcktjump \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 16)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ rcktjump2re \n€”‚ rcktpro \n€•‚ realmd1 \n€–‚ rfort \n€—‚ rj3 \n€˜‚ rjart2fb \n€™‚ rjart2va \n€š‚ rjart2vf \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 17)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ rjart3bf \n€”‚ rjart3vfr \n€•‚ rjdelite \n€–‚ rjextb01 \n€—‚ rjhella1 \n€˜‚ rjmpadv6 \n€™‚ rjmpadvf \n€š‚ rjracer \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 18)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ rock2 \n€”‚ sandrena \n€•‚ scout \n€–‚ scoutin \n€—‚ se2 \n€˜‚ se2vote \n€™‚ sewer1 \n€š‚ shoop \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 19)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ skywardf \n€”‚ snip2all \n€•‚ sniprwar \n€–‚ spaz4 \n€—‚ spit2 \n€˜‚ sprj2fb \n€™‚ spy_vs_spy \n€š‚ sq1 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 20)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ sq2 \n€”‚ sq3 \n€•‚ sq6 \n€–‚ svalley4 \n€—‚ svalley4sta \n€˜‚ swamp3 \n€™‚ tater \n€š‚ tf2k \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 21)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ tomb3 \n€”‚ torque3 \n€•‚ tower \n€–‚ town12 \n€—‚ town2 \n€˜‚ town4 \n€™‚ try6 \n€š‚ try7 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 22)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ turtle \n€”‚ tvote \n€•‚ unholyk \n€–‚ vote1 \n€—‚ vote40 \n€˜‚ votemap \n€™‚ vplay \n€š‚ walmarta \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 23)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ warehouse2 \n€”‚ weird \n€•‚ well1 \n€–‚ well6 \n€—‚ woodfort \n€˜‚ work3 \n€™‚ xpress2 \n€š‚ xpress3 \n€›‚ Next Menu \n€0‚ Nothing \n");
	}
	if (self.vote_menu == 24)
	{
		CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ xtrmrjb1 \n€”‚ z7 \n€•‚ north1 \n€›‚ Reset List \n€0‚ Nothing     \n");
	}

//	CenterPrint(self, "€ Vote Map Menu ‚\n\n€“‚ ThunderVote\n€”‚ Toaster    \n€•‚ Drop #3    \n€–‚ Holograph  \n€—‚ NightVision\n€˜‚ Lay Mode   \n€™‚ Taunt Menu \n€š‚ Yell Menu  \n€›‚ VoteMap    \n€0‚ Nothing    \n");
};

void(float inp) Menu_Vote_Input = 
{
	string put;
	if (self.vote_menu == 0)
	{
		if (inp == 1)
		{
			put = "1on1fort";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "1on1fortc";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "1on1forts";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "1on1r";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "1on1r2";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "1on1rpro";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "2castles";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "2farms";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 1)
	{
		if (inp == 1)
		{
			put = "2farms_olde";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "2fort4r";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "2FORT5";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "2fort5fel";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "2fort5p";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "2fort5r";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "2fort5sta";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "2fortflood";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 2)
	{
		if (inp == 1)
		{
			put = "2mach1";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "2machse";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "2mfield4";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "2mtf5";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "2night2";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "2nuke2";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "2octa4v1";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "2on2fortb2";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 3)
	{
		if (inp == 1)
		{
			put = "2skool3";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "2sphinx6";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "2tech4";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "32smooth";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "32smoothfel";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "32smoothsta";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "4f4";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "4f5_havoc";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 4)
	{
		if (inp == 1)
		{
			put = "adjmpvb3";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "adjmpvf1";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "airfox";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "alcatraz";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "arenasix";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "autobase";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "avihous";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "aztec1";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 5)
	{
		if (inp == 1)
		{
			put = "bam4";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "bam4sta";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "bam4_mega";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "bases";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "beer";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "beer2";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "bfort";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "blitzkrieg2";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 6)
	{
		if (inp == 1)
		{
			put = "blitzkrieg2_mega";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "blue1";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "border1";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "border1r";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "box3";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "brdgdeth";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "breach2";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "bridge2";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 7)
	{
		if (inp == 1)
		{
			put = "bridgep";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "bringit";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "bunnyhop";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "bunyhop2";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "canalzon";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "canyon1";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "caverns";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "choosenow";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 8)
	{
		if (inp == 1)
		{
			put = "church";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "circle";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "circle1";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "cjump1r";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "crap1on1";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "cryptic1";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "cube";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "demorox5";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 9)
	{
		if (inp == 1)
		{
			put = "demoz3";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "dinner";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "disorder";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "ditch2";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "dune1";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "dune1sta";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "egypt";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "Empbat";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 10)
	{
		if (inp == 1)
		{
			put = "endif";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "engbat";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "engbatxr";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "engjump2";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "engjumps";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "excel";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "extrj2b3";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "f4f";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 11)
	{
		if (inp == 1)
		{
			put = "fcast";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "flagcap";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "flash3e";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "FLASH3~1";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "free4all2";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "freeway";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "frontlin";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "futureq";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 12)
	{
		if (inp == 1)
		{
			put = "h4rdcore";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "helo_sub4";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "hunt2000";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "hunted";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "huntedr";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "iceland3";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "impact1";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "insanity2";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 13)
	{
		if (inp == 1)
		{
			put = "invade4a";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "jgpcity4";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "knockout";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "mbasesr";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "medic";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "medic3rr";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "mini32s";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "mininoheros";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 14)
	{
		if (inp == 1)
		{
			put = "nano2";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "noheros";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "p1on12";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "p1on1vF";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "parafort2";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "pipejump";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "pipelan";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "pipes";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 15)
	{
		if (inp == 1)
		{
			put = "povhop02";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "povmed2";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "preskool";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "pskills";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "psq1f";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "qdeth3";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "rckteer";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "rcktjump";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 16)
	{
		if (inp == 1)
		{
			put = "rcktjump2re";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "rcktpro";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "realmd1";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "rfort";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "rj3";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "rjart2fb";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "rjart2va";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "rjart2vf";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 17)
	{
		if (inp == 1)
		{
			put = "rjart3bf";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "rjart3vfr";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "rjdelite";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "rjextb01";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "rjhella1";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "rjmpadv6";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "rjmpadvf";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "rjracer";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 18)
	{
		if (inp == 1)
		{
			put = "rock2";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "sandrena";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "scout";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "scoutin";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "se2";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "se2vote";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "sewer1";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "shoop";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 19)
	{
		if (inp == 1)
		{
			put = "skywardf";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "snip2all";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "sniprwar";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "spaz4";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "spit2";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "sprj2fb";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "spy_vs_spy";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "sq1";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 20)
	{
		if (inp == 1)
		{
			put = "sq2";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "sq3";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "sq6";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "svalley4";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "svalley4sta";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "swamp3";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "tater";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "tf2k";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 21)
	{
		if (inp == 1)
		{
			put = "tomb3";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "torque3";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "tower";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "town12";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "town2";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "town4";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "try6";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "try7";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 22)
	{
		if (inp == 1)
		{
			put = "turtle";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "tvote";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "unholyk";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "vote1";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "vote40";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "votemap";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "vplay";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "walmarta";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 23)
	{
		if (inp == 1)
		{
			put = "warehouse2";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "weird";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "well1";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						put = "well6";
						votemap_start(put);
					}
					else
					{
						if (inp == 5)
						{
							put = "woodfort";
							votemap_start(put);
						}
						else
						{
							if (inp == 6)
							{
								put = "work3";
								votemap_start(put);
							}
							else
							{
								if (inp == 7)
								{
									put = "xpress2";
									votemap_start(put);
								}
								else
								{
									if (inp == 8)
									{
										put = "xpress3";
										votemap_start(put);
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = self.test_input + 1;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 24)
	{
		if (inp == 1)
		{
			put = "xtrmrjb1";
			votemap_start(put);
		}
		else
		{
			if (inp == 2)
			{
				put = "z7";
				votemap_start(put);
			}
			else
			{
				if (inp == 3)
				{
					put = "north1";
					votemap_start(put);
				}
				else
				{
					if (inp == 4)
					{
						self.test_input = 0;
						ResetMenu();
						stuffcmd(self, "votemenu\n");
					}
					else
					{
						if (inp == 5)
						{
							self.test_input = 0;
							ResetMenu();
							stuffcmd(self, "votemenu\n");
						}
						else
						{
							if (inp == 6)
							{
								self.test_input = 0;
								ResetMenu();
								stuffcmd(self, "votemenu\n");
							}
							else
							{
								if (inp == 7)
								{
									self.test_input = 0;
									ResetMenu();
									stuffcmd(self, "votemenu\n");
								}
								else
								{
									if (inp == 8)
									{
										self.test_input = 0;
										ResetMenu();
										stuffcmd(self, "votemenu\n");
									}
									else
									{
										if (inp == 9)
										{
											self.test_input = 0;
											ResetMenu();
											stuffcmd(self, "votemenu\n");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	if (self.vote_menu == 25)
	{
		self.test_input = 0;
		ResetMenu();
		stuffcmd(self, "votemenu\n");
	}
	ResetMenu();
	self.impulse = TF_FLARE_LIT;
};
//END
