.void()     th_turn;
.void()     spawnfunction;
vector ( vector ang ) SUB_NormalizeAngles;
void (entity srcent, entity destent) SUB_CopyEntity;
void( vector loc, float rad, float damage, float dur, float pause, float vol) multi_explosion;
void(string targ, vector orig) become_decoy;
void() RotateTargets;
void() RotateTargetsFinal;
void() SetTargetOrigin;
void() LinkRotateTargets;
#define mtf_coop_hipnotic
//end
